PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
construct {
    ?id schema:name ?name ;
        a schema:Person ;
        schema:partOf ?graph, ?graph2  ;
        schema:sameAs ?adid ;
        schema:missing  ?id2, ?adid2 .
}
where {
    values ?graph {
         <graph_placeholder>
    }
    graph ?graph {
        ?id a schema:Person  ;
            schema:name ?name .
        filter(!contains(str(?id),"artsdata.ca/resource/K"))
        bind(str(?name) as ?name_str)
    }
    optional {
        ?adid schema:sameAs ?id 
        filter(contains(str(?adid),"artsdata.ca/resource/K"))
    }
    optional {
        ?id schema:sameAs ?adid_anyType
        filter(contains(str(?adid),"artsdata.ca/resource/K"))
        bind(URI(?adid_anyType) as ?adid)
    }
    optional {
        graph ?graph2 {
            ?place2 a schema:Place ;
                    schema:name ?name_str .
            filter ( ?place != ?place2  )
            filter (?graph2 != ?graph )
        }
        optional {
            ?adid2 schema:sameAs ?place2 
        }
    }
} order by  ?name_sort